#!/usr/bin/env node
/**
 * Bundler for the modular DailyCoder Apps Script backend.
 *
 * Google Apps Script projects are flat in the cloud and you deploy by pasting a
 * single script. This script concatenates the modular sources under `src/`
 * (in filename order) into one deployable file at `dist/Code.gs`.
 *
 * Load order matters: config -> core -> feature modules -> router. The numeric
 * filename prefixes (00-, 01-, 10-, 20-) guarantee that order so the router's
 * dispatch-table literals can reference already-defined module namespaces.
 *
 * Usage:  node scripts/apps-script/build.mjs   (or `npm run build:gas`)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');
const OUT_FILE = path.join(DIST_DIR, 'Code.gs');

function main() {
  if (!fs.existsSync(SRC_DIR)) {
    console.error('[build:gas] Missing source directory:', SRC_DIR);
    process.exit(1);
  }

  const files = fs
    .readdirSync(SRC_DIR)
    .filter((f) => f.endsWith('.js'))
    .sort();

  if (!files.length) {
    console.error('[build:gas] No .js source files found in', SRC_DIR);
    process.exit(1);
  }

  const header = [
    '/**',
    ' * DailyCoder — Apps Script backend (GENERATED FILE — DO NOT EDIT BY HAND).',
    ' *',
    ' * Generated by scripts/apps-script/build.mjs from scripts/apps-script/src/*.js.',
    ' * Edit the modular sources under src/ and re-run `npm run build:gas`, then',
    ' * paste THIS file into the Apps Script editor and create a new deployment version.',
    ' *',
    ` * Built: ${new Date().toISOString()}`,
    ` * Modules: ${files.join(', ')}`,
    ' */',
    '',
  ].join('\n');

  const parts = files.map((file) => {
    const body = fs.readFileSync(path.join(SRC_DIR, file), 'utf8').replace(/\s+$/, '');
    return `// ═══════════════════════════════════════════════════════════════════════\n` +
      `// ${file}\n` +
      `// ═══════════════════════════════════════════════════════════════════════\n\n` +
      body + '\n';
  });

  const output = header + '\n' + parts.join('\n') + '\n';

  fs.mkdirSync(DIST_DIR, { recursive: true });
  fs.writeFileSync(OUT_FILE, output, 'utf8');

  console.log(`[build:gas] Bundled ${files.length} module(s) → ${path.relative(process.cwd(), OUT_FILE)}`);
  console.log('[build:gas] Files:', files.join(', '));
}

main();
